# Generated by Django 4.2.30 on 2026-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environment", "0017_gpuaccelerator_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpuaccelerator",
            name="memory_type",
            field=models.CharField(
                choices=[
                    ("GDDR6", "GDDR6"),
                    ("HBM2e", "HBM2e"),
                    ("HBM2", "HBM2"),
                    ("GDDR5", "GDDR5"),
                    ("HBM3", "HBM3"),
                ],
                max_length=32,
            ),
        ),
    ]
